### ISSUE TITLE
Adjust .gitignore

### ISSUE THREAD

**Issue by mikhailsirenko** [WKSu/compound-events#16]
Hola señor!

It's seems that you forgot to add `.ipynb_checkpoints/` to your .gitignore file which is absolutely unacceptable. As a result, while browsing the experiments folder I immediately got lost. Please fix it ASAP.

Kind regards,
Mikhail

**Comment by WKSu** [comment]
Thanks Mikhail! This should be fixed now - I will be sure to make use of the other guidelines mentioned in your [reproducible workshop](https://humtechlab.gitbook.io/redcar/1-reproducible). 

This prompted me to notice that we haven't added a license and a requirements.txt which are fixed as well!
